# Generated by Django 5.2 on 2025-04-21 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apadrinhados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('estilo_vida', models.IntegerField(blank=True, null=True)),
                ('estilo_vida_outro', models.TextField(blank=True, null=True)),
                ('area_escolar', models.IntegerField(blank=True, null=True)),
                ('area_escolar_outro', models.TextField(blank=True, null=True)),
                ('tempo_livre', models.IntegerField(blank=True, null=True)),
                ('tempo_livre_outro', models.TextField(blank=True, null=True)),
                ('inspiracao', models.IntegerField(blank=True, null=True)),
                ('inspiracao_outro', models.TextField(blank=True, null=True)),
                ('valor_representa', models.IntegerField(blank=True, null=True)),
                ('valor_representa_outro', models.TextField(blank=True, null=True)),
                ('extra', models.IntegerField(blank=True, null=True)),
                ('extra_outro', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
