# Generated by Django 5.2 on 2025-04-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apadrinhados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('genero', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
