# Generated by Django 5.2 on 2025-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadrinhados',
            name='padrinhos',
            field=models.ManyToManyField(blank=True, related_name='apadrinhados', to='institutoSolidare.padrinho'),
        ),
    ]
