# Generated by Django 5.2 on 2025-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0002_apadrinhados_padrinhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadrinhados',
            name='area_escolar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='estilo_vida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='extra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='inspiracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='palavras_chave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='tempo_livre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apadrinhados',
            name='valor_representa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
