# Generated by Django 5.2 on 2025-04-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0002_padrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrinho',
            name='area_escolar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='area_escolar_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='estilo_vida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='estilo_vida_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='extra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='extra_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='inspiracao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='inspiracao_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='tempo_livre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='tempo_livre_outro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='valor_representa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='padrinho',
            name='valor_representa_outro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
