# Generated by Django 5.2 on 2025-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0003_apadrinhados_area_escolar_apadrinhados_estilo_vida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadrinhados',
            name='info',
            field=models.CharField(default='antigo', max_length=200),
            preserve_default=False,
        ),
    ]
