# Generated by Django 5.2 on 2025-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutoSolidare', '0004_apadrinhados_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='apadrinhados',
            name='foto_para_padrinho',
            field=models.ImageField(default='foto', upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
