# Generated by Django 5.2 on 2025-06-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apadrinhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('foto_para_padrinho', models.ImageField(upload_to='fotos/')),
                ('info', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('area_escolar', models.IntegerField(blank=True, null=True)),
                ('profissao_desejada', models.IntegerField(blank=True, null=True)),
                ('hobby', models.IntegerField(blank=True, null=True)),
                ('inspiracoes', models.IntegerField(blank=True, null=True)),
                ('valores', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('endereco', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('numero_rua', models.CharField(max_length=50)),
                ('complemento_rua', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('area_escolar', models.IntegerField(blank=True, null=True)),
                ('profissao_atual', models.IntegerField(blank=True, null=True)),
                ('hobby', models.IntegerField(blank=True, null=True)),
                ('inspiracoes', models.IntegerField(blank=True, null=True)),
                ('valores', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='padrinho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('aprovada', models.BooleanField(default=False)),
                ('respondida', models.BooleanField(default=False)),
                ('remetente_tipo', models.CharField(choices=[('padrinho', 'Padrinho'), ('apadrinhado', 'Apadrinhado')], max_length=20)),
                ('apadrinhado', models.ForeignKey(blank=True, help_text='Referência ao apadrinhado envolvido (remetente ou destinatário).', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.apadrinhado')),
                ('padrinho', models.ForeignKey(blank=True, help_text='Referência ao padrinho envolvido (remetente ou destinatário).', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.padrinho')),
            ],
        ),
        migrations.AddField(
            model_name='apadrinhado',
            name='padrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apadrinhados', to='apadrinhamento.padrinho'),
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('publica', models.BooleanField(default=False)),
                ('apadrinhado', models.ForeignKey(blank=True, help_text='Somente para cartas privadas. Deixe em branco para cartas públicas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.apadrinhado')),
                ('likes', models.ManyToManyField(blank=True, related_name='publicacoes_curtidas', to='apadrinhamento.padrinho')),
                ('padrinho', models.ForeignKey(blank=True, help_text='Somente para cartas privadas. Deixe em branco para cartas públicas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.padrinho')),
            ],
        ),
    ]
