# Generated by Django 5.2 on 2025-06-02 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('area_escolar', models.IntegerField(blank=True, null=True)),
                ('profissao_desejada_quando_crianca', models.IntegerField(blank=True, null=True)),
                ('profissao_atual', models.IntegerField(blank=True, null=True)),
                ('hobby', models.IntegerField(blank=True, null=True)),
                ('inspiracoes', models.IntegerField(blank=True, null=True)),
                ('valores', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('publica', models.BooleanField(default=False)),
                ('padrinho', models.ForeignKey(blank=True, help_text='Somente para cartas privadas. Deixe em branco para cartas públicas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.padrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Apadrinhados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('foto_para_padrinho', models.ImageField(upload_to='fotos/')),
                ('info', models.CharField(max_length=200)),
                ('area_escolar', models.IntegerField(blank=True, null=True)),
                ('profissao_desejada', models.IntegerField(blank=True, null=True)),
                ('hobby', models.IntegerField(blank=True, null=True)),
                ('inspiracoes', models.IntegerField(blank=True, null=True)),
                ('valores', models.IntegerField(blank=True, null=True)),
                ('padrinhos', models.ManyToManyField(blank=True, related_name='apadrinhados', to='apadrinhamento.padrinho')),
            ],
        ),
    ]
