# Generated by Django 5.2 on 2025-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padrinho',
            old_name='estado',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='idade',
        ),
        migrations.AddField(
            model_name='padrinho',
            name='complemento_rua',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='padrinho',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
