# Generated by Django 5.2 on 2025-06-02 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carta',
            new_name='Publicacao',
        ),
    ]
