# Generated by Django 5.2 on 2025-06-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0002_rename_estado_padrinho_cidade_remove_padrinho_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrinho',
            name='numero_rua',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
