# Generated by Django 5.2 on 2025-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0003_padrinho_numero_rua'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrinho',
            name='nome_completo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
