# Generated by Django 5.2 on 2025-06-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0005_alter_padrinho_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos/'),
            preserve_default=False,
        ),
    ]
