# Generated by Django 5.2 on 2025-06-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0006_publicacao_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='remetente_tipo',
            field=models.CharField(choices=[('padrinho', 'Padrinho'), ('apadrinhado', 'Apadrinhado')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carta',
            name='apadrinhado',
            field=models.ForeignKey(blank=True, help_text='Referência ao apadrinhado envolvido (remetente ou destinatário).', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.apadrinhado'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='padrinho',
            field=models.ForeignKey(blank=True, help_text='Referência ao padrinho envolvido (remetente ou destinatário).', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.padrinho'),
        ),
    ]
