# Generated by Django 5.2 on 2025-06-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0007_carta_remetente_tipo_alter_carta_apadrinhado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apadrinhado',
            name='idade',
        ),
    ]
