# Generated by Django 5.2 on 2025-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0008_remove_apadrinhado_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='respondida',
            field=models.BooleanField(default=False),
        ),
    ]
