# Generated by Django 5.2 on 2025-06-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0009_carta_respondida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrinho',
            name='profissao_desejada_quando_crianca',
        ),
        migrations.AddField(
            model_name='apadrinhado',
            name='endereco',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
