# Generated by Django 5.2 on 2025-06-03 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0010_remove_padrinho_profissao_desejada_quando_crianca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='apadrinhado',
            field=models.ForeignKey(blank=True, help_text='Somente para cartas privadas. Deixe em branco para cartas públicas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='apadrinhamento.apadrinhado'),
        ),
    ]
