# Generated by Django 5.2 on 2025-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0010_remove_padrinho_profissao_desejada_quando_crianca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='publicacoes_curtidas', to='apadrinhamento.padrinho'),
        ),
    ]
