# Generated by Django 5.2 on 2025-06-03 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0011_publicacao_apadrinhado'),
        ('apadrinhamento', '0012_publicacao_likes'),
    ]

    operations = [
    ]
