from apadrinhamento.views import *
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", new_home, name="home"),
    path("EN/", new_homeEN, name="homeEN"),
    path("ES/", new_homeES, name="homeES"),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    # ---------------------------------
    path("padrinho/login/", padrinho_login, name="padrinhoLogin"),
    path("padrinho/cadastro-explicativo/", padrinho_cadastro_explicativo, name="padrinhoCadastroExplicativo"),
    path("padrinho/questionario/<int:indice>/", padrinho_questionario, name="padrinhoQuestionario"),
    path('padrinho/salvar-respostas/', padrinho_salvar_respostas, name='padrinhoSalvarRespostas'),
    path("padrinho/criar-usuario/", padrinho_criar_usuario, name="padrinhoCriarUsuario"),
    path("padrinho/cadastro/", padrinho_cadastro, name="padrinhoCadastro"),
    path("padrinho/escolher-apadrinhado/", padrinho_escolher_apadrinhado, name="padrinhoEscolherApadrinhado"),
    path("padrinho/escolher-apadrinhado-deslogado/", padrinho_escolher_apadrinhado_deslogado, name="padrinhoEscolherApadrinhadoDeslogado"),
    path("padrinho/doacao/<int:apadrinhado_id>/", padrinho_doacao, name="padrinhoDoacao"),
    path('padrinho/feed/', padrinho_feed, name='padrinhoFeed'),
    path('padrinho/perfil/', padrinho_perfil, name='padrinhoPerfil'),
    path("padrinho/perfil/valores/", padrinho_alterar_valores, name="padrinhoAlterarValores"),
    path('padrinho/doacao-livre/', padrinho_doacao_livre, name='padrinhoDoacaoLivre'),
    path('padrinho/doacao-livre-checkout/', padrinho_doacao_livre_checkout, name='padrinhoDoacaoLivreCheckout'),
    path('padrinho/meus-apadrinhados/', padrinho_meus_apadrinhados, name='padrinhoMeusApadrinhados'),
    path('padrinho/cartas/', padrinho_cartas, name = 'cartas'),
    path('padrinho/cartas/escrita/', escrita_cartas, name ='cartas_escrita'),
    path('padrinho/cartas/enviadas/', padrinho_cartas_enviadas, name ='padrinhoCartasEnviadas'),
    # ---------------------------------
    path('adm/login/', adm_login ,name="admLogin"),
    path('adm/home/', adm_home, name="admHome"),
    path('adm/gerenciar-afilhados/', lista_afilhados, name='gerenciarAfilhados'),
    path('adm/gerenciar-afilhados/<int:apadrinhado_id>', editar_afilhado, name='editarAfilhado'),
    path('adm/excluir/<int:apadrinhado_id>/', excluir_afilhado, name='excluir_afilhado'),
    path('adm/gerenciar-feed/', adm_gerenciar_feed, name='gerenciarFeed'),
    path('adm/novo-post/', adm_novo_post, name='novoPost'),
    path('adm/gerenciar-cartas/', adm_gerenciar_cartas, name='gerenciarCartas'),
    path('adm/aprovar-carta/<int:id>/', aprovar_carta, name='aprovarCarta'),
    path('adm/rejeitar-carta/<int:id>/', rejeitar_carta, name='rejeitarCarta'),
    path('adm/escrever-carta/', adm_escrever_carta, name='admEscreverCarta'),
    path('adm/programado/', adm_programado, name='admProgramado'),
    path('adm/respondidas/', adm_respondidas, name='admRespondidas'),
    path("afilhados/novo/", cadastrar_afilhado, name="cadastrarAfilhado"),
    path("afilhados/editar-post/<int:id>/", adm_editar_post, name="admEditarPost"),
]
