# Generated by Django 5.2 on 2025-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apadrinhamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apadrinhado',
            name='foto',
            field=models.ImageField(default='fotos/foto_padrao.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='apadrinhado',
            name='foto_para_padrinho',
            field=models.ImageField(default='fotos/foto_padrao.jpg', upload_to='fotos/'),
        ),
        migrations.AlterField(
            model_name='padrinho',
            name='foto',
            field=models.ImageField(default='fotos/foto_padrao.jpg', upload_to='fotos/'),
        ),
    ]
